services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.16
    environment:
      POSTGRES_USER: uservice
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
